In [49]:
import pandas as pd
from collections import OrderedDict, defaultdict

In [50]:
s = pd.Series([1, 2, 3, 4], index=['A', 'B', 'C', 'D'])
s.to_dict()

{'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [51]:
s.to_dict(into=OrderedDict)  # 有序字典

OrderedDict([('A', 1), ('B', 2), ('C', 3), ('D', 4)])

In [52]:
dd = defaultdict(list)  # 默认字典
s.to_dict(into=dd)

defaultdict(list, {'A': 1, 'B': 2, 'C': 3, 'D': 4})

In [53]:
df = pd.DataFrame({'col1': [1, 2],
                   'col2': [0.5, 0.75]},
                  index=['row1', 'row2'])
df

      col1  col2
row1     1  0.50
row2     2  0.75

In [54]:
# 默认
# dict like {column -> {index -> value}}
df.to_dict()  # 默认orient='dict'

{'col1': {'row1': 1, 'row2': 2}, 'col2': {'row1': 0.5, 'row2': 0.75}}

In [ ]:
df_new = pd.DataFrame(df.to_dict())
df_new  # 恢复回DataFrame

      col1  col2
row1     1  0.50
row2     2  0.75

In [56]:
# dict like {index -> {column -> value}}
df.to_dict(orient='index')

{'row1': {'col1': 1, 'col2': 0.5}, 'row2': {'col1': 2, 'col2': 0.75}}

In [57]:
# dict like {column -> [values]}
df.to_dict('list')

{'col1': [1, 2], 'col2': [0.5, 0.75]}

In [58]:
# dict like {column -> Series(values)}
df.to_dict('series')

{'col1': row1    1
 row2    2
 Name: col1, dtype: int64,
 'col2': row1    0.50
 row2    0.75
 Name: col2, dtype: float64}

In [59]:
# dict like {‘index’ -> [index], ‘columns’ -> [columns], ‘data’ -> [values]}
df.to_dict('split')

{'index': ['row1', 'row2'],
 'columns': ['col1', 'col2'],
 'data': [[1, 0.5], [2, 0.75]]}

In [60]:
# ict like {‘index’ -> [index], ‘columns’ -> [columns], ‘data’ -> [values], ‘index_names’ -> [index.names], ‘column_names’ -> [column.names]}
df.to_dict('tight')

{'index': ['row1', 'row2'],
 'columns': ['col1', 'col2'],
 'data': [[1, 0.5], [2, 0.75]],
 'index_names': [None],
 'column_names': [None]}